name: Vitest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: vitest-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup.yml
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Build project
      run: npm run build --if-present
    - name: Run tests
      run: npm test
